# Generated by Django 5.0 on 2024-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDisplayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_period', models.CharField(choices=[('Breakfast/Lunch', 'Breakfast/Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('section', models.CharField(choices=[('MenuItem', 'Menu Item'), ('Ingredient', 'Ingredient'), ('Bread', 'Bread')], max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity_type', models.CharField(choices=[('Grams', 'Grams'), ('Kilograms', 'Kilograms'), ('Numbers', 'Numbers')], max_length=10)),
            ],
        ),
    ]
