# Generated by Django 5.0 on 2024-10-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_dailydisplayassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_lunch_start_time', models.TimeField(blank=True, null=True)),
                ('breakfast_lunch_end_time', models.TimeField(blank=True, null=True)),
                ('dinner_start_time', models.TimeField(blank=True, null=True)),
                ('dinner_end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
